// demo-antd3/src/SwitchDemo.tsx
import React, { useState } from 'react'
import { Switch, Radio } from 'antd'
const { Group: RadioGroup } = Radio

/**
 * Switch 全形态矩阵 —— 与 demo/src/components/SwitchDemo.vue 严格对位。
 *
 * 状态：开关（可交互）/ 关闭禁用 / 开启禁用。
 * 文字：默认关闭；开启后显示各自状态名。位置默认右侧，可切左侧（互斥，一个开关一个标签）。
 *
 * ⚠ 与 EP 差异：EP 用 el-switch 的 active-text/inactive-text 内建外置文字；
 *   antd3 的 checkedChildren/unCheckedChildren 是「内嵌」在轨道里的，语义不同。
 *   为对齐 EP 的「文字外置于开关两侧」版式，这里用外层 span 自行渲染文字，
 *   不走 antd3 内嵌文字（见 antd3-theme/DIFF.md 的 Switch 文字位置差异）。
 */
function LabeledSwitch(props: {
  label: string
  showText: boolean
  position: 'left' | 'right'
  checked?: boolean
  disabled?: boolean
  onChange?: (checked: boolean) => void
}) {
  const { label, showText, position, checked, disabled, onChange } = props
  const text = showText ? <span className="switch-label">{label}</span> : null
  return (
    <span className="switch-field">
      {position === 'left' && text}
      <Switch checked={checked} disabled={disabled} onChange={onChange} />
      {position === 'right' && text}
    </span>
  )
}

export default function SwitchDemo() {
  const [value, setValue] = useState(true)
  const [showText, setShowText] = useState(false)
  const [position, setPosition] = useState<'left' | 'right'>('right')

  return (
    <section className="demo-section">
      <h2 className="demo-section__title">Switch 开关 —— antd 3 适配层</h2>

      <div className="demo-block control-showcase">
        <div className="control-showcase__main">
          <p className="demo-desc">
            需要表示开关状态/两种状态之间的切换时使用，和 checkbox 的区别是，切换 switch
            会直接触发状态改变，而 checkbox 一般用于状态标记，需要和提交操作配合。
          </p>
          <div className="demo-row">
            <LabeledSwitch
              label="开关"
              showText={showText}
              position={position}
              checked={value}
              onChange={setValue}
            />
            <LabeledSwitch label="关闭禁用" showText={showText} position={position} disabled checked={false} />
            <LabeledSwitch label="开启禁用" showText={showText} position={position} disabled checked />
          </div>
        </div>
        <aside className="config-card">
          <p className="config-card__title">配置项</p>
          <div className="config-form">
            <div className="config-item">
              <span className="config-item__label">文字</span>
              <Switch checked={showText} onChange={setShowText} />
            </div>
            <div className="config-item">
              <span className="config-item__label">文字位置</span>
              <RadioGroup
                value={position}
                disabled={!showText}
                onChange={(e) => setPosition(e.target.value)}
              >
                <Radio value="right">右侧</Radio>
                <Radio value="left">左侧</Radio>
              </RadioGroup>
            </div>
          </div>
        </aside>
      </div>
    </section>
  )
}

// demo/src/components/SwitchDemo.vue
<template>
  <section id="switch" class="demo-section">
    <h2 class="demo-section__title">Switch 开关</h2>

    <div class="demo-block control-showcase">
      <div class="control-showcase__main">
        <p class="demo-desc">需要表示开关状态/两种状态之间的切换时使用，和 checkbox 的区别是，切换 switch 会直接触发状态改变，而 checkbox 一般用于状态标记，需要和提交操作配合。</p>
        <!-- 文字开关切换 switch 文字标签是否显示；关闭（默认）则只留开关本体。
             位置默认右侧（active-text，EP 默认渲染在右）；仅当开关左侧无内容、
             右侧存在其他内容时才改用 inactive-text 置左，避免文字与右侧内容挤在
             一起归属不清。两者互斥，一个开关只配一个标签。
             字重 / spacing-2 间距 / 常态与禁用态取色全在源头 switch.scss。
             文字内容为各自的状态名：开关 / 关闭禁用 / 开启禁用。 -->
        <div class="demo-row">
          <el-switch
            v-model="switchValue1"
            :active-text="textOnRight ? '开关' : undefined"
            :inactive-text="textOnLeft ? '开关' : undefined"
          />
          <el-switch
            disabled :model-value="false"
            :active-text="textOnRight ? '关闭禁用' : undefined"
            :inactive-text="textOnLeft ? '关闭禁用' : undefined"
          />
          <el-switch
            disabled :model-value="true"
            :active-text="textOnRight ? '开启禁用' : undefined"
            :inactive-text="textOnLeft ? '开启禁用' : undefined"
          />
        </div>
      </div>
      <aside class="config-card">
        <p class="config-card__title">配置项</p>
        <el-form :model="switchConfigForm" label-width="auto">
          <el-form-item label="文字">
            <el-switch v-model="switchShowText" />
          </el-form-item>
          <!-- 位置仅在「文字」开启时可选；关闭文字后无位置可言，故置灰。
               两个互斥选项、需并排比较 → 用 Radio 而非 Select（见 select-pattern） -->
          <el-form-item label="文字位置">
            <el-radio-group v-model="switchTextPosition" :disabled="!switchShowText">
              <el-radio value="right">右侧</el-radio>
              <el-radio value="left">左侧</el-radio>
            </el-radio-group>
          </el-form-item>
        </el-form>
      </aside>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref, reactive, computed } from 'vue'

const switchValue1 = ref(true)

// Switch 文字：默认关闭（不展示 active-text / inactive-text），开启则显示状态名
const switchShowText = ref(false)
// 文字位置：默认右侧（active-text）。左侧（inactive-text）是窄条件例外——
// 仅当开关左侧无内容、右侧存在其他内容时才用，避免文字与右侧内容挤在一起。
const switchTextPosition = ref<'left' | 'right'>('right')
const textOnRight = computed(() => switchShowText.value && switchTextPosition.value === 'right')
const textOnLeft = computed(() => switchShowText.value && switchTextPosition.value === 'left')
const switchConfigForm = reactive({ switchShowText, switchTextPosition })
</script>
