// demo-antd3/src/components/UserAvatar.tsx
import { Avatar } from 'antd'
import { AVATAR_MAP, type AvatarRole } from '../avatar-roles'

export default function UserAvatar(props: {
  role?: AvatarRole
  src?: string
  size?: number
  shape?: 'circle' | 'square'
}) {
  const { role, src, size = 40, shape = 'circle' } = props
  const finalSrc = src ?? (role ? AVATAR_MAP[role] : undefined)
  return <Avatar size={size} src={finalSrc} shape={shape} />
}

// demo/src/components/UserAvatar.vue
<template>
  <el-avatar :size="size" :src="src" :shape="shape" />
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { AVATAR_MAP, type AvatarRole } from './avatar-roles'

const props = withDefaults(
  defineProps<{
    /** 角色，命中内置头像时使用对应图片 */
    role?: AvatarRole
    /** 自定义头像地址，优先级高于 role */
    src?: string
    size?: number | 'large' | 'default' | 'small'
    shape?: 'circle' | 'square'
  }>(),
  {
    size: 40,
    shape: 'circle',
  },
)

const src = computed(() => props.src ?? (props.role ? AVATAR_MAP[props.role] : undefined))
</script>
