// demo/src/components/CheckboxDemo.vue
<template>
  <section id="checkbox" class="demo-section">
    <h2 class="demo-section__title">Checkbox 多选框</h2>

    <div class="demo-block control-showcase">
      <div class="control-showcase__main">
        <p class="demo-desc">单独使用可以表示两种状态之间的切换，和 switch 类似。区别在于切换 switch 会直接触发状态改变，而 checkbox 一般用于状态标记，需要和提交操作配合。</p>
        <!-- checkbox-inline-row：让 group 内两项与后面四个独立项在 flex 里成为平级等距子项
             （group 盒子 display:contents 透明化，与 radio-inline-row 同一手法，纯排版不碰组件外观） -->
        <div class="demo-row checkbox-inline-row">
          <!-- 状态清单顺序：选中 / 未选 / 半选 / 选中禁用 / 未选禁用 / 半选禁用
               （三个常态在前、三个禁用态在后）。仅「选中」「未选」两个可交互项进 group 的 v-model；
               半选、选中禁用、未选禁用、半选禁用均为纯状态展示（indeterminate / disabled 直接置位，不进 group）。 -->
          <el-checkbox-group v-model="checkboxValue">
            <el-checkbox :label="checkboxShowText ? '选中' : ''" value="vue" />
            <el-checkbox :label="checkboxShowText ? '未选' : ''" value="react" />
          </el-checkbox-group>
          <el-checkbox :indeterminate="true" :label="checkboxShowText ? '半选' : ''" />
          <el-checkbox :model-value="true" disabled :label="checkboxShowText ? '选中禁用' : ''" />
          <el-checkbox :model-value="false" disabled :label="checkboxShowText ? '未选禁用' : ''" />
          <el-checkbox :indeterminate="true" disabled :label="checkboxShowText ? '半选禁用' : ''" />
        </div>
      </div>
      <aside class="config-card">
        <p class="config-card__title">配置项</p>
        <el-form :model="checkboxConfigForm" label-width="auto">
          <el-form-item label="文字">
            <el-switch v-model="checkboxShowText" />
          </el-form-item>
        </el-form>
      </aside>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'

const checkboxValue = ref(['vue'])

// 配置卡：文字是否显示（关闭则只留选择控件本体）
const checkboxShowText = ref(true)
const checkboxConfigForm = reactive({ checkboxShowText })
</script>

<style scoped>


/* Checkbox 六态平级等距：group 盒子 display:contents 透明化，让「选中/未选」两项与后面
   四个独立展示项都成为 .demo-row(flex) 的直接子项，六个平级等距（与 radio-inline-row 同手法）。 */
.checkbox-inline-row :deep(.el-checkbox-group) {
  display: contents;
}
/* 抹掉源头 el-checkbox 的 margin-inline-end(16px)，间距统一交给 .demo-row 的 gap 管，避免叠加 */
.checkbox-inline-row :deep(.el-checkbox) {
  margin-inline-end: 0;
}
</style>

// demo-antd3/src/CheckboxDemo.tsx
import React, { useState } from 'react'
import { Checkbox, Switch } from 'antd'
const CheckboxGroup = Checkbox.Group

/**
 * Checkbox 全形态矩阵 —— 与 demo/src/components/CheckboxDemo.vue 严格对位。
 *
 * 状态清单顺序：选中 / 未选 / 半选 / 选中禁用 / 未选禁用 / 半选禁用
 * （三个常态在前、三个禁用态在后）。仅「选中」「未选」两项进 group 的受控值；
 * 半选、三个禁用态均为纯状态展示（indeterminate / disabled 直接置位，不进 group）。
 * 用 checkbox-inline-row 让 group 内两项与后面四个独立项在 flex 里平级等距。
 */
export default function CheckboxDemo() {
  const [value, setValue] = useState<string[]>(['vue'])
  const [showText, setShowText] = useState(true)

  return (
    <section className="demo-section">
      <h2 className="demo-section__title">Checkbox 多选框 —— antd 3 适配层</h2>

      <div className="demo-block control-showcase">
        <div className="control-showcase__main">
          <p className="demo-desc">
            单独使用可以表示两种状态之间的切换，和 switch 类似。区别在于切换 switch
            会直接触发状态改变，而 checkbox 一般用于状态标记，需要和提交操作配合。
          </p>
          <div className="demo-row checkbox-inline-row">
            <CheckboxGroup value={value} onChange={(v) => setValue(v as string[])}>
              <Checkbox value="vue">{showText ? '选中' : ''}</Checkbox>
              <Checkbox value="react">{showText ? '未选' : ''}</Checkbox>
            </CheckboxGroup>
            <Checkbox indeterminate>{showText ? '半选' : ''}</Checkbox>
            <Checkbox checked disabled>{showText ? '选中禁用' : ''}</Checkbox>
            <Checkbox disabled>{showText ? '未选禁用' : ''}</Checkbox>
            <Checkbox indeterminate disabled>{showText ? '半选禁用' : ''}</Checkbox>
          </div>
        </div>
        <aside className="config-card">
          <p className="config-card__title">配置项</p>
          <div className="config-form">
            <div className="config-item">
              <span className="config-item__label">文字</span>
              <Switch checked={showText} onChange={setShowText} />
            </div>
          </div>
        </aside>
      </div>
    </section>
  )
}
