// demo-antd3/src/App.tsx
import React, { useMemo, useState } from 'react'

import ButtonDemo from './ButtonDemo'
import RadioDemo from './RadioDemo'
import CheckboxDemo from './CheckboxDemo'
import SwitchDemo from './SwitchDemo'
import TooltipDemo from './TooltipDemo'
import InputDemo from './InputDemo'
import DropdownDemo from './DropdownDemo'
import TagDemo from './TagDemo'
import BreadcrumbDemo from './BreadcrumbDemo'
import TabsDemo from './TabsDemo'
import PaginationDemo from './PaginationDemo'
import AnchorDemo from './AnchorDemo'
import StepsDemo from './StepsDemo'
import SelectDemo from './SelectDemo'
import DatePickerDemo from './DatePickerDemo'
import SliderDemo from './SliderDemo'
import RateDemo from './RateDemo'
import CellDemo from './CellDemo'
import BadgeDemo from './BadgeDemo'
import DescriptionsDemo from './DescriptionsDemo'
import AvatarDemo from './AvatarDemo'
import EmptyDemo from './EmptyDemo'
import DialogDemo from './DialogDemo'
import DrawerDemo from './DrawerDemo'
import MessageDemo from './MessageDemo'
import AlertDemo from './AlertDemo'
import NotificationDemo from './NotificationDemo'
import PopconfirmDemo from './PopconfirmDemo'
import LoadingDemo from './LoadingDemo'
import SkeletonDemo from './SkeletonDemo'
import ResultDemo from './ResultDemo'
import PaletteDemo from './token/PaletteDemo'
import SemanticColorDemo from './token/SemanticColorDemo'
import FontBaseDemo from './token/FontBaseDemo'
import FontSemanticDemo from './token/FontSemanticDemo'
import SpacingDemo from './token/SpacingDemo'
import RadiusDemo from './token/RadiusDemo'
import ShadowDemo from './token/ShadowDemo'
import MotionDemo from './token/MotionDemo'
import IconDemo from './token/IconDemo'

/**
 * antd 3 规范站页面框架 —— 与 demo/src/App.vue 的骨架对位。
 *
 * 结构：顶栏（品牌 + 分类导航）+ 左侧栏（随分类切换的菜单）+ 内容区。
 * 说明：
 *   - 顶部分类、侧栏分组均由 TOP_TABS 数据驱动，逐条来自 Vue 版 App.vue；
 *   - 目前只有「基础组件」下的 Button / Radio 是真实内容（render 字段），
 *     其余菜单项内容留空，用统一占位面板兜住；
 *   - 试点阶段 antd3 版暂不迁移 Vue 版的品牌色 / 亮暗风格切换。
 */

type MenuItem = {
  key: string
  label: string
  render?: () => React.ReactNode
}

type MenuGroup = {
  label?: string
  items: MenuItem[]
}

type TopTab = {
  value: string
  label: string
  groups: MenuGroup[]
}

const TOP_TABS: TopTab[] = [
  {
    value: 'token',
    label: '基础样式',
    groups: [
      {
        items: [
          { key: 'palette', label: 'Palette 基础色板', render: () => <PaletteDemo /> },
          { key: 'token-color', label: 'Color 语义色板', render: () => <SemanticColorDemo /> },
          { key: 'token-font-base', label: 'Font Base 基础字阶', render: () => <FontBaseDemo /> },
          { key: 'token-font-semantic', label: 'Font 语义字阶', render: () => <FontSemanticDemo /> },
          { key: 'token-spacing', label: 'Spacing 间距', render: () => <SpacingDemo /> },
          { key: 'token-radius', label: 'Radius 圆角', render: () => <RadiusDemo /> },
          { key: 'token-shadow', label: 'Shadow 阴影', render: () => <ShadowDemo /> },
          { key: 'token-motion', label: 'Motion 动效', render: () => <MotionDemo /> },
          { key: 'token-icon', label: 'Icon 图标', render: () => <IconDemo /> },
        ],
      },
    ],
  },
  {
    value: 'component',
    label: '基础组件',
    groups: [
      {
        label: '通用',
        items: [{ key: 'button', label: 'Button 按钮', render: () => <ButtonDemo /> }],
      },
      {
        label: '导航',
        items: [
          { key: 'breadcrumb', label: 'Breadcrumb 面包屑', render: () => <BreadcrumbDemo /> },
          { key: 'tabs', label: 'Tabs 标签页', render: () => <TabsDemo /> },
          { key: 'pagination', label: 'Pagination 分页', render: () => <PaginationDemo /> },
          { key: 'anchor', label: 'Anchor 锚点', render: () => <AnchorDemo /> },
          { key: 'steps', label: 'Steps 轻量步骤条', render: () => <StepsDemo /> },
          { key: 'dropdown', label: 'Dropdown 下拉菜单', render: () => <DropdownDemo /> },
        ],
      },
      {
        label: '数据录入',
        items: [
          { key: 'input', label: 'Input 输入框', render: () => <InputDemo /> },
          { key: 'select', label: 'Select 选择器', render: () => <SelectDemo /> },
          { key: 'date-picker', label: 'Picker 时间/日期选择器', render: () => <DatePickerDemo /> },
          { key: 'radio', label: 'Radio 单选框', render: () => <RadioDemo /> },
          { key: 'checkbox', label: 'Checkbox 多选框', render: () => <CheckboxDemo /> },
          { key: 'switch', label: 'Switch 开关', render: () => <SwitchDemo /> },
          { key: 'slider', label: 'Slider 滑块', render: () => <SliderDemo /> },
          { key: 'rate', label: 'Rate 评分', render: () => <RateDemo /> },
        ],
      },
      {
        label: '数据展示',
        items: [
          { key: 'tag', label: 'Tag 标签', render: () => <TagDemo /> },
          { key: 'cell', label: 'Cell 单元格', render: () => <CellDemo /> },
          { key: 'badge', label: 'Badge 徽标', render: () => <BadgeDemo /> },
          { key: 'descriptions', label: 'Descriptions 描述列表', render: () => <DescriptionsDemo /> },
          { key: 'avatar', label: 'Avatar 头像', render: () => <AvatarDemo /> },
          { key: 'empty', label: 'Empty 空状态', render: () => <EmptyDemo /> },
        ],
      },
      {
        label: '反馈',
        items: [
          { key: 'dialog', label: 'Dialog 对话框', render: () => <DialogDemo /> },
          { key: 'drawer', label: 'Drawer 抽屉', render: () => <DrawerDemo /> },
          { key: 'message', label: 'Message 消息提示', render: () => <MessageDemo /> },
          { key: 'alert', label: 'Alert 警告', render: () => <AlertDemo /> },
          { key: 'notification', label: 'Notification 通知', render: () => <NotificationDemo /> },
          { key: 'popconfirm', label: 'Popconfirm 气泡确认框', render: () => <PopconfirmDemo /> },
          { key: 'tooltip', label: 'Tooltip 文字提示', render: () => <TooltipDemo /> },
          { key: 'loading', label: 'Loading 加载', render: () => <LoadingDemo /> },
          { key: 'skeleton', label: 'Skeleton 骨架屏', render: () => <SkeletonDemo /> },
          { key: 'result', label: 'Result 结果页', render: () => <ResultDemo /> },
        ],
      },
    ],
  },
  {
    value: 'business',
    label: '业务组件',
    groups: [
      {
        items: [
          { key: 'page-frame', label: 'PageFrame 页面框架' },
          { key: 'step-bar', label: 'StepBar 步骤条' },
          { key: 'ai-button', label: 'AiButton Ai按钮' },
          { key: 'picked-item', label: 'PickedItem 已选项' },
          { key: 'option-card', label: 'OptionCard 卡片单选' },
        ],
      },
    ],
  },
  {
    value: 'chart',
    label: '图表组件',
    groups: [
      {
        items: [
          { key: 'chart-line', label: 'Line 折线图' },
          { key: 'chart-bar', label: 'Bar 柱状图' },
          { key: 'chart-bar-horizontal', label: 'Horizontal 条形图' },
          { key: 'chart-donut', label: 'Donut 环形图' },
          { key: 'chart-pie', label: 'Pie 饼状图' },
          { key: 'chart-bar-line', label: 'Bar-Line 柱线图' },
          { key: 'chart-radar', label: 'Radar 雷达图' },
          { key: 'chart-scatter', label: 'Scatter 散点图' },
          { key: 'chart-bar-stack', label: 'Stacked 堆积柱状图' },
          { key: 'chart-bar-stack-h', label: 'Stacked-H 堆积条形图' },
          { key: 'chart-bar-percent', label: 'Percent 百分比堆积' },
          { key: 'chart-diverging', label: 'Diverging 双向柱状图' },
        ],
      },
    ],
  },
  {
    value: 'pattern',
    label: '设计模式',
    groups: [
      {
        items: [
          { key: 'pattern-form-org', label: 'Form 表单组织' },
          { key: 'pattern-form', label: 'Form Layout 表单布局' },
          { key: 'pattern-list-item', label: 'List Item 列表条目' },
          { key: 'pattern-toolbar', label: 'Toolbar 工具栏布局' },
        ],
      },
    ],
  },
  {
    value: 'page',
    label: '典型页面',
    groups: [
      {
        items: [
          { key: 'page-public-info', label: 'Public 公开信息设置' },
          { key: 'page-course-tools', label: 'Course Tools 课程工具' },
          { key: 'page-course-dashboard', label: 'Profile 课程画像' },
          { key: 'page-ai-quiz', label: 'AI Quiz AI 出题' },
        ],
      },
    ],
  },
  {
    value: 'copywriting',
    label: '文案规范',
    groups: [
      {
        items: [
          { key: 'copywriting-time', label: 'Time 通用时间' },
          { key: 'copywriting-number', label: 'Number 数字' },
        ],
      },
    ],
  },
  {
    value: 'judging',
    label: '评判标准',
    groups: [
      {
        items: [
          { key: 'judging-intro', label: 'Overview 说明' },
          { key: 'judging-list', label: 'Checklist 检查清单' },
        ],
      },
    ],
  },
]

const flattenItems = (tab: TopTab): MenuItem[] =>
  tab.groups.reduce<MenuItem[]>((acc, group) => acc.concat(group.items), [])

/** 内容为空的菜单项统一用此占位（tab 已建，内容待补） */
function Placeholder({ label }: { label: string }) {
  return (
    <section className="demo-section">
      <h2 className="demo-section__title">{label}</h2>
      <div className="demo-placeholder">该子页面尚未实现，敬请期待。</div>
    </section>
  )
}

export default function App() {
  const [currentTopTab, setCurrentTopTab] = useState('component')
  const [activeKey, setActiveKey] = useState('button')

  const activeTab = useMemo(
    () => TOP_TABS.find((t) => t.value === currentTopTab) ?? TOP_TABS[0],
    [currentTopTab],
  )

  const activeItem = useMemo(
    () => flattenItems(activeTab).find((item) => item.key === activeKey),
    [activeTab, activeKey],
  )

  const handleTopTab = (tab: TopTab) => {
    setCurrentTopTab(tab.value)
    const first = flattenItems(tab)[0]
    if (first) setActiveKey(first.key)
  }

  return (
    <>
      <header className="app-topbar">
        <div className="app-topbar__brand">
          <div className="app-topbar__logo">
            <img src="/logo.png" alt="Xiaoya Theme" />
          </div>
          <div>
            <div className="app-topbar__title">Xiaoya Theme</div>
            <div className="app-topbar__subtitle">antd 3 主题演示</div>
          </div>
        </div>
        <nav className="app-topbar__nav">
          {TOP_TABS.map((tab) => (
            <button
              key={tab.value}
              type="button"
              className={
                'app-topbar__nav-item' +
                (tab.value === currentTopTab ? ' is-active' : '')
              }
              onClick={() => handleTopTab(tab)}
            >
              {tab.label}
            </button>
          ))}
        </nav>
      </header>

      <div className="app-layout">
        <aside className="app-sidebar">
          <div className="app-sidebar__nav-wrap">
            {activeTab.groups.map((group, gi) => (
              <div key={group.label ?? gi}>
                {group.label && (
                  <div className="app-sidebar__group-label">{group.label}</div>
                )}
                <ul className="app-sidebar__nav">
                  {group.items.map((item) => (
                    <li key={item.key}>
                      <a
                        href={`#${item.key}`}
                        className={item.key === activeKey ? 'is-active' : undefined}
                        onClick={(e) => {
                          e.preventDefault()
                          setActiveKey(item.key)
                        }}
                      >
                        {item.label}
                        {!item.render && (
                          <span className="app-sidebar__todo-badge">未接入</span>
                        )}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </aside>

        <main className="app-content">
          {activeItem?.render ? (
            activeItem.render()
          ) : (
            <Placeholder label={activeItem?.label ?? ''} />
          )}
        </main>
      </div>
    </>
  )
}

// demo/src/App.vue
<template>
  <el-config-provider :locale="epLocale">
  <header class="app-topbar">
    <div class="app-topbar__brand">
      <div class="app-topbar__logo">
        <img src="/logo.png" alt="Xiaoya Theme" />
      </div>
      <div>
        <div class="app-topbar__title">Xiaoya Theme</div>
        <div class="app-topbar__subtitle">Element Plus 主题演示</div>
      </div>
    </div>
    <el-tabs v-model="currentTopTab" class="app-topbar__nav">
      <el-tab-pane
        v-for="tab in topTabs"
        :key="tab.value"
        :label="tab.label"
        :name="tab.value"
      />
    </el-tabs>
    <div class="app-topbar__theme">
      <div class="brand-switcher">
        <!-- 预置品牌：dot 自带 data-brand，命中该品牌色板作用域后 accent-6 即其主色 -->
        <button
          v-for="b in presetBrands"
          :key="b.value"
          type="button"
          class="brand-dot"
          :class="{ 'is-active': currentBrand === b.value }"
          :data-brand="b.value"
          :title="b.label"
          @click="currentBrand = b.value"
        />
        <!-- 自定义：点击弹出浮层，输入 16 进制色值作为主色。
             色点默认黑底 + 下拉箭头，选定后即所选色，选中态与预置色点同款外框 -->
        <!-- audit-ignore 品牌色自定义浮层：需承载输入框+按钮的可交互内容，
             dropdown 只能放选项、dialog 对这个轻量操作过重。经确认保留 el-popover -->
        <el-popover
          v-model:visible="customPanelVisible"
          :width="280"
          placement="bottom-end"
          trigger="click"
          popper-class="custom-color-popover"
          @before-enter="customColorInput = customColor"
        >
          <template #reference>
            <button
              type="button"
              class="brand-dot brand-dot--custom"
              :class="{ 'is-active': currentBrand === CUSTOM_BRAND }"
              :style="{ background: customColor }"
              title="自定义主色"
            >
              <ChevronDown :size="14" class="brand-dot__caret" />
            </button>
          </template>

          <div class="custom-color-panel">
            <el-input
              v-model="customColorInput"
              placeholder="请输入十六进制色值作为主色"
              @keyup.enter="confirmCustomColor"
            />
            <div class="custom-color-panel__footer">
              <el-button @click="cancelCustomColor">取消</el-button>
              <el-button type="primary" @click="confirmCustomColor">确定</el-button>
            </div>
          </div>
        </el-popover>
      </div>
      <button
        type="button"
        class="theme-toggle"
        :title="isDark ? '切换到亮色' : '切换到暗色'"
        @click="isDark = !isDark"
      >
        <Moon v-if="isDark" :size="18" />
        <Sun v-else :size="18" />
      </button>
    </div>
  </header>
  <div class="app-layout">
    <aside class="app-sidebar">
      <el-scrollbar class="app-sidebar__nav-wrap" view-class="app-sidebar__nav-view">
        <template v-if="currentTopTab === 'token'">
        <ul class="app-sidebar__nav">
          <li><a href="#palette" :class="{ 'is-active': activeSection === 'palette' }">Palette 基础色板</a></li>
          <li><a href="#token-color" :class="{ 'is-active': activeSection === 'token-color' }">Color 语义色板</a></li>
          <li><a href="#token-font-base" :class="{ 'is-active': activeSection === 'token-font-base' }">Font Base 基础字阶</a></li>
          <li><a href="#token-font-semantic" :class="{ 'is-active': activeSection === 'token-font-semantic' }">Font 语义字阶</a></li>
          <li><a href="#token-spacing" :class="{ 'is-active': activeSection === 'token-spacing' }">Spacing 间距</a></li>
          <li><a href="#token-radius" :class="{ 'is-active': activeSection === 'token-radius' }">Radius 圆角</a></li>
          <li><a href="#token-shadow" :class="{ 'is-active': activeSection === 'token-shadow' }">Shadow 阴影</a></li>
          <li><a href="#token-motion" :class="{ 'is-active': activeSection === 'token-motion' }">Motion 动效</a></li>
          <li><a href="#token-icon" :class="{ 'is-active': activeSection === 'token-icon' }">Icon 图标</a></li>
        </ul>
        </template>

        <template v-if="currentTopTab === 'component'">
        <div class="app-sidebar__group-label">通用</div>
        <ul class="app-sidebar__nav">
          <li><a href="#button" :class="{ 'is-active': activeSection === 'button' }">Button 按钮</a></li>
          <!-- <li><a href="#button-examples" :class="{ 'is-active': activeSection === 'button-examples' }" style="color: var(--iflyv-brand-primary);">📋 Button Examples（临时预览）</a></li> -->
        </ul>

        <div class="app-sidebar__group-label">导航</div>
        <ul class="app-sidebar__nav">
          <li><a href="#breadcrumb" :class="{ 'is-active': activeSection === 'breadcrumb' }">Breadcrumb 面包屑</a></li>
          <li><a href="#tabs" :class="{ 'is-active': activeSection === 'tabs' }">Tabs 标签页</a></li>
          <li><a href="#pagination" :class="{ 'is-active': activeSection === 'pagination' }">Pagination 分页</a></li>
          <li><a href="#anchor" :class="{ 'is-active': activeSection === 'anchor' }">Anchor 锚点</a></li>
          <li><a href="#steps" :class="{ 'is-active': activeSection === 'steps' }">Steps 轻量步骤条</a></li>
          <li><a href="#dropdown" :class="{ 'is-active': activeSection === 'dropdown' }">Dropdown 下拉菜单</a></li>
        </ul>

        <div class="app-sidebar__group-label">数据录入</div>
        <ul class="app-sidebar__nav">
          <li><a href="#input" :class="{ 'is-active': activeSection === 'input' }">Input 输入框</a></li>
          <li><a href="#select" :class="{ 'is-active': activeSection === 'select' }">Select 选择器</a></li>
          <!-- <li><a href="#select-examples" :class="{ 'is-active': activeSection === 'select-examples' }" style="color: var(--iflyv-brand-primary);">📋 Select Examples（临时预览）</a></li> -->
          <li><a href="#date-picker" :class="{ 'is-active': activeSection === 'date-picker' }">Picker 时间/日期选择器</a></li>
          <li><a href="#radio" :class="{ 'is-active': activeSection === 'radio' }">Radio 单选框</a></li>
          <li><a href="#checkbox" :class="{ 'is-active': activeSection === 'checkbox' }">Checkbox 多选框</a></li>
          <li><a href="#switch" :class="{ 'is-active': activeSection === 'switch' }">Switch 开关</a></li>
          <li><a href="#slider" :class="{ 'is-active': activeSection === 'slider' }">Slider 滑块</a></li>
          <li><a href="#rate" :class="{ 'is-active': activeSection === 'rate' }">Rate 评分</a></li>
          <!-- Upload 上传：暂时用不到，先注释保留，需要时放开 -->
          <!-- <li><a href="#upload" :class="{ 'is-active': activeSection === 'upload' }">Upload 上传</a></li> -->
          <!-- Transfer 穿梭框：暂时用不到，先注释保留，需要时放开 -->
          <!-- <li><a href="#transfer" :class="{ 'is-active': activeSection === 'transfer' }">Transfer 穿梭框</a></li> -->
        </ul>

        <div class="app-sidebar__group-label">数据展示</div>
        <ul class="app-sidebar__nav">
          <li><a href="#tag" :class="{ 'is-active': activeSection === 'tag' }">Tag 标签</a></li>
          <li><a href="#table" :class="{ 'is-active': activeSection === 'table' }">Cell 单元格</a></li>
          <!-- <li><a href="#table-examples" :class="{ 'is-active': activeSection === 'table-examples' }" style="color: var(--iflyv-brand-primary);">📋 Table Examples（临时预览）</a></li> -->
          <li><a href="#badge" :class="{ 'is-active': activeSection === 'badge' }">Badge 徽标</a></li>
          <li><a href="#descriptions" :class="{ 'is-active': activeSection === 'descriptions' }">Descriptions 描述列表</a></li>
          <li><a href="#avatar" :class="{ 'is-active': activeSection === 'avatar' }">Avatar 头像</a></li>
          <li><a href="#empty" :class="{ 'is-active': activeSection === 'empty' }">Empty 空状态</a></li>
          <!-- DataDisplay 数据展示：徽标/描述列表已拆出、骨架屏已移入反馈组，页内暂无在展内容（仅存暂停块），先注释，需要时放开 -->
          <!-- <li><a href="#data-display" :class="{ 'is-active': activeSection === 'data-display' }">DataDisplay 数据展示</a></li> -->
        </ul>

        <div class="app-sidebar__group-label">反馈</div>
        <ul class="app-sidebar__nav">
          <li><a href="#dialog" :class="{ 'is-active': activeSection === 'dialog' }">Dialog 对话框</a></li>
          <!-- <li><a href="#dialog-examples" :class="{ 'is-active': activeSection === 'dialog-examples' }" style="color: var(--iflyv-brand-primary);">📋 Dialog Examples（临时预览）</a></li> -->
          <li><a href="#drawer" :class="{ 'is-active': activeSection === 'drawer' }">Drawer 抽屉</a></li>
          <li><a href="#message" :class="{ 'is-active': activeSection === 'message' }">Message 消息提示</a></li>
          <li><a href="#alert" :class="{ 'is-active': activeSection === 'alert' }">Alert 警告</a></li>
          <li><a href="#notification" :class="{ 'is-active': activeSection === 'notification' }">Notification 通知</a></li>
          <li><a href="#popconfirm" :class="{ 'is-active': activeSection === 'popconfirm' }">Popconfirm 气泡确认框</a></li>
          <li><a href="#tooltip" :class="{ 'is-active': activeSection === 'tooltip' }">Tooltip 文字提示</a></li>
          <li><a href="#loading" :class="{ 'is-active': activeSection === 'loading' }">Loading 加载</a></li>
          <li><a href="#skeleton" :class="{ 'is-active': activeSection === 'skeleton' }">Skeleton 骨架屏</a></li>
          <li><a href="#result" :class="{ 'is-active': activeSection === 'result' }">Result 结果页</a></li>
        </ul>

        <!-- 其他组：Empty 已移入「数据展示」；Other 结果页拆出后页内暂无在展内容（仅存暂停块），整组先注释，需要时放开 -->
        <!-- <div class="app-sidebar__group-label">其他</div>
        <ul class="app-sidebar__nav">
          <li><a href="#other" :class="{ 'is-active': activeSection === 'other' }">Other 其他组件</a></li>
        </ul> -->
        </template>

        <template v-if="currentTopTab === 'business'">
        <!-- 业务组件层导航：随组件逐个加入（如 AiPanel 等） -->
        <ul class="app-sidebar__nav">
          <li><a href="#page-frame" :class="{ 'is-active': activeSection === 'page-frame' }">PageFrame 页面框架</a></li>
          <li><a href="#step-bar" :class="{ 'is-active': activeSection === 'step-bar' }">StepBar 步骤条</a></li>
          <li><a href="#ai-button" :class="{ 'is-active': activeSection === 'ai-button' }">AiButton Ai按钮</a></li>
        </ul>
        </template>

        <template v-if="currentTopTab === 'pattern'">
        <ul class="app-sidebar__nav">
          <li><a href="#pattern-form-org" :class="{ 'is-active': activeSection === 'pattern-form-org' }">Form 表单组织</a></li>
          <li><a href="#pattern-form" :class="{ 'is-active': activeSection === 'pattern-form' }">Form Layout 表单布局</a></li>
          <li><a href="#pattern-list-item" :class="{ 'is-active': activeSection === 'pattern-list-item' }">List Item 列表条目</a></li>
          <li><a href="#pattern-toolbar" :class="{ 'is-active': activeSection === 'pattern-toolbar' }">Toolbar 工具栏布局</a></li>
        </ul>
        </template>

        <template v-if="currentTopTab === 'page'">
        <ul class="app-sidebar__nav">
          <li><a href="#page-public-info" :class="{ 'is-active': activeSection === 'page-public-info' }">Public 公开信息设置</a></li>
          <li><a href="#page-course-tools" :class="{ 'is-active': activeSection === 'page-course-tools' }">Course Tools 课程工具</a></li>
          <li><a href="#page-course-dashboard" :class="{ 'is-active': activeSection === 'page-course-dashboard' }">Profile 课程画像</a></li>
        </ul>
        </template>

        <template v-if="currentTopTab === 'copywriting'">
        <ul class="app-sidebar__nav">
          <li><a href="#copywriting-time" :class="{ 'is-active': activeSection === 'copywriting-time' }">Time 通用时间</a></li>
        </ul>
        </template>

        <template v-if="currentTopTab === 'chart'">
        <ul class="app-sidebar__nav">
          <li><a href="#chart-line" :class="{ 'is-active': activeSection === 'chart-line' }">Line 折线图</a></li>
          <li><a href="#chart-bar" :class="{ 'is-active': activeSection === 'chart-bar' }">Bar 柱状图</a></li>
          <li><a href="#chart-bar-horizontal" :class="{ 'is-active': activeSection === 'chart-bar-horizontal' }">Horizontal 条形图</a></li>
          <li><a href="#chart-donut" :class="{ 'is-active': activeSection === 'chart-donut' }">Donut 环形图</a></li>
          <li><a href="#chart-pie" :class="{ 'is-active': activeSection === 'chart-pie' }">Pie 饼状图</a></li>
          <li><a href="#chart-bar-line" :class="{ 'is-active': activeSection === 'chart-bar-line' }">Bar-Line 柱线图</a></li>
          <li><a href="#chart-radar" :class="{ 'is-active': activeSection === 'chart-radar' }">Radar 雷达图</a></li>
          <li><a href="#chart-scatter" :class="{ 'is-active': activeSection === 'chart-scatter' }">Scatter 散点图</a></li>
          <li><a href="#chart-bar-stack" :class="{ 'is-active': activeSection === 'chart-bar-stack' }">Stacked 堆积柱状图</a></li>
          <li><a href="#chart-bar-stack-h" :class="{ 'is-active': activeSection === 'chart-bar-stack-h' }">Stacked-H 堆积条形图</a></li>
          <li><a href="#chart-bar-percent" :class="{ 'is-active': activeSection === 'chart-bar-percent' }">Percent 百分比堆积</a></li>
          <li><a href="#chart-diverging" :class="{ 'is-active': activeSection === 'chart-diverging' }">Diverging 双向柱状图</a></li>
        </ul>
        </template>

        <template v-if="currentTopTab === 'judging'">
        <ul class="app-sidebar__nav">
          <li><a href="#judging-intro" :class="{ 'is-active': activeSection === 'judging-intro' }">Overview 说明</a></li>
          <li><a href="#judging-list" :class="{ 'is-active': activeSection === 'judging-list' }">Checklist 检查清单</a></li>
        </ul>
        </template>
      </el-scrollbar>
    </aside>

    <main class="app-content">
      <div v-show="currentTopTab === 'token'">
      <PaletteDemo />
      <SemanticColorDemo />
      <FontBaseDemo />
      <FontSemanticDemo />
      <SpacingDemo />
      <RadiusDemo />
      <ShadowDemo />
      <MotionDemo />
      <IconDemo />
      </div>
      <div v-show="currentTopTab === 'component'" class="no-title-divider">
      <ButtonDemo />
      <!-- <section id="button-examples" class="demo-section" style="border-top: 2px dashed var(--iflyv-brand-primary); padding-top: var(--iflyv-spacing-6); margin-top: var(--iflyv-spacing-6);">
        <h2 class="demo-section__title">📋 Button Examples（design-spec/examples/ 临时预览）</h2>
        <p style="color: var(--iflyv-text-3); margin-bottom: var(--iflyv-spacing-4); font-size: 13px;">
          这是 design-spec/examples/button.examples.vue 的渲染效果。
          反模式（注释中的代码）不会渲染，只展示推荐写法。验收完毕可移除本 section。
        </p>
        <ButtonExamples />
      </section> -->
      <BreadcrumbDemo />
      <TabsDemo />
      <PaginationDemo />
      <AnchorDemo />
      <StepsDemo />
      <DropdownDemo />
      <InputDemo />
      <SelectDemo />
      <!-- <section id="select-examples" class="demo-section" style="border-top: 2px dashed var(--iflyv-brand-primary); padding-top: var(--iflyv-spacing-6); margin-top: var(--iflyv-spacing-6);">
        <h2 class="demo-section__title">📋 Select Examples（design-spec/examples/ 临时预览）</h2>
        <p style="color: var(--iflyv-text-3); margin-bottom: var(--iflyv-spacing-4); font-size: 13px;">
          design-spec/examples/select.examples.vue 的渲染效果。反模式仅在源码注释中。
        </p>
        <SelectExamples />
      </section> -->
      <DatePickerDemo />
      <RadioDemo />
      <CheckboxDemo />
      <SwitchDemo />
      <SliderDemo />
      <RateDemo />
      <!-- Upload 上传：暂时用不到，先注释保留，需要时放开 -->
      <!-- <UploadDemo /> -->
      <!-- Transfer 穿梭框：暂时用不到，先注释保留，需要时放开 -->
      <!-- <TransferDemo /> -->
      <TagDemo />
      <TableDemo />
      <!-- <section id="table-examples" class="demo-section" style="border-top: 2px dashed var(--iflyv-brand-primary); padding-top: var(--iflyv-spacing-6); margin-top: var(--iflyv-spacing-6);">
        <h2 class="demo-section__title">📋 Table Examples（design-spec/examples/ 临时预览）</h2>
        <p style="color: var(--iflyv-text-3); margin-bottom: var(--iflyv-spacing-4); font-size: 13px;">
          design-spec/examples/table.examples.vue 的渲染效果。反模式仅在源码注释中。
        </p>
        <TableExamples />
      </section> -->
      <BadgeDemo />
      <DescriptionsDemo />
      <AvatarDemo />
      <EmptyDemo />
      <!-- DataDisplay 数据展示：页内暂无在展内容（仅存暂停块），随导航一并注释，需要时放开 -->
      <!-- <DataDisplayDemo /> -->
      <DialogDemo />
      <!-- <section id="dialog-examples" class="demo-section" style="border-top: 2px dashed var(--iflyv-brand-primary); padding-top: var(--iflyv-spacing-6); margin-top: var(--iflyv-spacing-6);">
        <h2 class="demo-section__title">📋 Dialog Examples（design-spec/examples/ 临时预览）</h2>
        <p style="color: var(--iflyv-text-3); margin-bottom: var(--iflyv-spacing-4); font-size: 13px;">
          design-spec/examples/dialog.examples.vue 的渲染效果。反模式仅在源码注释中。
        </p>
        <DialogExamples />
      </section> -->
      <DrawerDemo />
      <MessageDemo />
      <AlertDemo />
      <NotificationDemo />
      <PopconfirmDemo />
      <TooltipDemo />
      <LoadingDemo />
      <SkeletonDemo />
      <ResultDemo />
      <!-- Other 其他组件：结果页拆出后页内暂无在展内容（仅存暂停块），先注释，需要时放开 -->
      <!-- <OtherDemo /> -->
      </div>
      <div v-show="currentTopTab === 'business'" class="no-title-divider">
      <PageFrameDemo />
      <StepBarDemo />
      <AiButtonDemo />
      </div>
      <div v-show="currentTopTab === 'pattern'" class="no-title-divider">
      <PatternFormOrgDemo />
      <PatternFormDemo />
      <PatternListItemDemo />
      <PatternToolbarDemo />
      </div>
      <div v-show="currentTopTab === 'page'" class="no-title-divider">
      <PublicInfoPageDemo />
      <CourseToolsPageDemo />
      <CourseDashboardPageDemo />
      </div>
      <div v-show="currentTopTab === 'copywriting'">
      <CopywritingTimeDemo />
      </div>
      <div v-show="currentTopTab === 'chart'" class="no-title-divider">
      <ChartSpecDemo />
      </div>
      <div v-show="currentTopTab === 'judging'" class="no-title-divider">
      <JudgingIntroDemo />
      <JudgingListDemo />
      </div>
    </main>
  </div>
  </el-config-provider>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch, nextTick } from 'vue'
import { ElConfigProvider, ElMessage } from 'element-plus'
import zhCn from 'element-plus/es/locale/lang/zh-cn'
import { Sun, Moon, ChevronDown } from 'lucide-vue-next'
import { generatePalette } from './utils/generate-palette'

// 顶部导航 tab
const topTabs = [
  { value: 'token', label: '基础样式' },
  { value: 'component', label: '基础组件' },
  { value: 'business', label: '业务组件' },
  { value: 'chart', label: '图表组件' },
  { value: 'pattern', label: '设计模式' },
  { value: 'page', label: '典型页面' },
  { value: 'copywriting', label: '文案规范' },
  { value: 'judging', label: '评判标准' },
]
const currentTopTab = ref('component')

// ============ 主题切换（品牌色 + 亮/暗）============
// ============ 主题切换（品牌色 + 亮/暗）============
// 预置品牌：值即 register-brand 注册的 name。
// ⚠ 注册在使用方（见本 demo 的 styles/global.scss 顶部），源头只提供 mixin——
//   下游项目要用自己的品牌色，同样在自己项目里 @include register-brand 注册。
const presetBrands = [
  { value: 'green', label: '品牌绿（默认）' },
  { value: 'science-blue', label: '理工蓝 #0077FF' },
]
const CUSTOM_BRAND = 'custom'

const currentBrand = ref('green')
// 自定义色默认黑（色点显示为黑底 + 白箭头）；仅当用户主动选色后才切到自定义品牌
const customColor = ref('#000000')
const isDark = ref(false)

// 自定义色：由主色算出 10 阶亮/暗色板，写成行内 CSS 变量覆盖 accent-1~10。
// 走行内 style 而非 scss 注册，是因为 register-brand 是编译期 mixin，接不了运行时色值。
function applyCustomPalette(color: string, dark: boolean) {
  const root = document.documentElement
  if (!color) {
    for (let i = 1; i <= 10; i += 1) root.style.removeProperty(`--iflyv-accent-${i}`)
    return
  }
  const palette = generatePalette(color, dark ? { theme: 'dark' } : {})
  palette.forEach((c, i) => root.style.setProperty(`--iflyv-accent-${i + 1}`, c))
}

const customPanelVisible = ref(false)
const customColorInput = ref('')

/** 取消：回落到首个预置主色（绿），自定义色点复位为黑 */
function cancelCustomColor() {
  customColorInput.value = ''
  customColor.value = '#000000'
  currentBrand.value = 'green'
  customPanelVisible.value = false
}

/** 确定：色值合法则应用为自定义主色，同时把选中态从预置色点移走 */
function confirmCustomColor() {
  const raw = customColorInput.value.trim()
  const hex = raw.startsWith('#') ? raw : `#${raw}`
  // 支持 #RGB 简写与 #RRGGBB
  if (!/^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(hex)) {
    ElMessage({ message: '请输入合法的十六进制色值，如 #0077FF', type: 'warning', showClose: true })
    return
  }
  // 简写补全成 6 位，供色板算法解析
  const full =
    hex.length === 4
      ? `#${hex[1]}${hex[1]}${hex[2]}${hex[2]}${hex[3]}${hex[3]}`
      : hex
  customColor.value = full.toUpperCase()
  currentBrand.value = CUSTOM_BRAND
  customPanelVisible.value = false
}

// 写到 html 上：[data-brand] 命中品牌色板、[data-theme="dark"] 命中暗色语义层
watch(
  [currentBrand, customColor, isDark],
  ([brand, color, dark]) => {
    const root = document.documentElement
    if (dark) root.dataset.theme = 'dark'
    else delete root.dataset.theme

    if (brand === CUSTOM_BRAND && color) {
      // 自定义色不走 [data-brand] 作用域，清掉它避免预置色板残留
      delete root.dataset.brand
      applyCustomPalette(color, dark as boolean)
    } else {
      applyCustomPalette('', false) // 清掉行内覆盖，交还给 scss 注册的色板
      root.dataset.brand = brand as string
    }
  },
  { immediate: true },
)

// 语言 locale（固定中文）
const epLocale = ref(zhCn)

import PaletteDemo from './components/PaletteDemo.vue'
import SemanticColorDemo from './components/token/SemanticColorDemo.vue'
import RadiusDemo from './components/token/RadiusDemo.vue'
import SpacingDemo from './components/token/SpacingDemo.vue'
import FontBaseDemo from './components/token/FontBaseDemo.vue'
import FontSemanticDemo from './components/token/FontSemanticDemo.vue'
import ShadowDemo from './components/token/ShadowDemo.vue'
import MotionDemo from './components/token/MotionDemo.vue'
import IconDemo from './components/token/IconDemo.vue'
import ButtonDemo from './components/ButtonDemo.vue'
import InputDemo from './components/InputDemo.vue'
import SelectDemo from './components/SelectDemo.vue'
import RadioDemo from './components/RadioDemo.vue'
import CheckboxDemo from './components/CheckboxDemo.vue'
import SwitchDemo from './components/SwitchDemo.vue'
import SliderDemo from './components/SliderDemo.vue'
import RateDemo from './components/RateDemo.vue'
import DatePickerDemo from './components/DatePickerDemo.vue'
// import UploadDemo from './components/UploadDemo.vue'  // ⏸ 暂停启用，需要时放开
// Transfer 穿梭框：暂时用不到，先注释保留，需要时放开
// import TransferDemo from './components/TransferDemo.vue'
import TagDemo from './components/TagDemo.vue'
import TableDemo from './components/TableDemo.vue'
import TabsDemo from './components/TabsDemo.vue'
import BreadcrumbDemo from './components/BreadcrumbDemo.vue'
import DropdownDemo from './components/DropdownDemo.vue'
import StepsDemo from './components/StepsDemo.vue'
import AnchorDemo from './components/AnchorDemo.vue'
import PaginationDemo from './components/PaginationDemo.vue'
// import DataDisplayDemo from './components/DataDisplayDemo.vue'  // ⏸ 暂停启用（页内暂无在展内容），需要时放开
import AvatarDemo from './components/AvatarDemo.vue'
import BadgeDemo from './components/BadgeDemo.vue'
import DescriptionsDemo from './components/DescriptionsDemo.vue'
import DialogDemo from './components/DialogDemo.vue'
import MessageDemo from './components/MessageDemo.vue'
import PopconfirmDemo from './components/PopconfirmDemo.vue'
import AlertDemo from './components/AlertDemo.vue'
import TooltipDemo from './components/TooltipDemo.vue'
import NotificationDemo from './components/NotificationDemo.vue'
import DrawerDemo from './components/DrawerDemo.vue'
import LoadingDemo from './components/LoadingDemo.vue'
import SkeletonDemo from './components/SkeletonDemo.vue'
import EmptyDemo from './components/EmptyDemo.vue'
import ResultDemo from './components/ResultDemo.vue'
// import OtherDemo from './components/OtherDemo.vue'  // ⏸ 暂停启用（页内暂无在展内容），需要时放开
import PatternFormOrgDemo from './components/pattern/PatternFormOrgDemo.vue'
import PatternFormDemo from './components/pattern/PatternFormDemo.vue'
import PatternListItemDemo from './components/pattern/PatternListItemDemo.vue'
import PatternToolbarDemo from './components/pattern/PatternToolbarDemo.vue'
import PublicInfoPageDemo from './components/page/PublicInfoPageDemo.vue'
import CourseToolsPageDemo from './components/page/CourseToolsPageDemo.vue'
import CourseDashboardPageDemo from './components/page/CourseDashboardPageDemo.vue'
import ChartSpecDemo from './components/chart/ChartSpecDemo.vue'
import CopywritingTimeDemo from './components/CopywritingTimeDemo.vue'
import JudgingIntroDemo from './components/JudgingIntroDemo.vue'
import JudgingListDemo from './components/JudgingListDemo.vue'
// 业务组件层 demo（引用 design-spec/components/）
import StepBarDemo from './components/biz/StepBarDemo.vue'
import PageFrameDemo from './components/biz/PageFrameDemo.vue'
import AiButtonDemo from './components/biz/AiButtonDemo.vue'
// 临时预览 examples 的 import（已注释挂载，需要时取消注释）：
// import ButtonExamples from '../../design-spec/examples/button.examples.vue'
// import FormExamples from '../../design-spec/examples/form.examples.vue'
// import TableExamples from '../../design-spec/examples/table.examples.vue'
// import DialogExamples from '../../design-spec/examples/dialog.examples.vue'
// import SelectExamples from '../../design-spec/examples/select.examples.vue'

// Scroll-spy: 高亮当前可见区域对应的导航项
const activeSection = ref('palette')

const sectionIds = [
  'palette', 'token-color', 'token-font-base', 'token-font-semantic', 'token-spacing', 'token-radius', 'token-shadow', 'token-motion', 'token-icon',
  'button',
  'breadcrumb', 'tabs', 'pagination', 'anchor', 'steps', 'dropdown',
  'input', 'select', 'date-picker', 'radio', 'checkbox', 'switch', 'slider', 'rate',
  'tag', 'table', 'badge', 'descriptions', 'avatar', 'empty',
  'dialog', 'drawer', 'message', 'alert', 'notification', 'popconfirm', 'tooltip', 'loading', 'skeleton', 'result',
  'page-frame', 'step-bar', 'ai-button',
  'pattern-form-org', 'pattern-form', 'pattern-list-item', 'pattern-toolbar',
  'page-public-info', 'page-course-tools', 'page-course-dashboard',
  'copywriting-time',
  'chart-line', 'chart-bar', 'chart-bar-horizontal', 'chart-donut', 'chart-pie', 'chart-bar-line',
  'chart-radar', 'chart-scatter', 'chart-bar-stack', 'chart-bar-stack-h', 'chart-bar-percent', 'chart-diverging',
  'judging-intro', 'judging-list',
]

// 每个顶部 tab 对应它的首个 section id，切 tab 时先兜底高亮该项，
// 避免某些 tab（如「设计模式」只有单个长 section）滚动观察器未触发导致导航不高亮。
const firstSectionByTab: Record<string, string> = {
  token: 'palette',
  component: 'button',
  business: 'page-frame',
  pattern: 'pattern-form-org',
  page: 'page-public-info',
  copywriting: 'copywriting-time',
  chart: 'chart-line',
  judging: 'judging-intro',
}

watch(currentTopTab, (tab) => {
  const first = firstSectionByTab[tab]
  if (first) activeSection.value = first
  // 切 tab 后 DOM 中可见 section 变化，重挂观察器让滚动高亮继续生效
  nextTick(observeSections)
})

// 确定性 scroll-spy：按滚动位置取「最后一个顶部越过停靠线的 section」。
// 之前用 IntersectionObserver 的「最后一个 isIntersecting 条目获胜」，向上滚动时
// 相邻两个 section 会短暂同时压在判定带上、后者获胜且离开事件被忽略，高亮卡在错误项。
// 停靠线与 html 的 scroll-padding-top 对齐（topbar 64 + spacing-3 12），再留少量容差。
const SPY_OFFSET = 64 + 12 + 8

let spyTicking = false

function updateActiveSection() {
  let current = ''
  for (const id of sectionIds) {
    const el = document.getElementById(id)
    if (!el || el.offsetParent === null) continue  // 跳过不存在或隐藏 tab 里的 section
    if (el.getBoundingClientRect().top <= SPY_OFFSET) {
      current = id  // 顶部已越线，暂记；继续找更靠后的
    } else {
      break  // sectionIds 按页面顺序排列，后面的更不可能越线
    }
  }
  if (current) {
    activeSection.value = current
  } else {
    // 还没有任何 section 越线（停在页面最顶端）→ 兜底高亮当前 tab 首项
    const first = firstSectionByTab[currentTopTab.value]
    if (first) activeSection.value = first
  }
}

function onSpyScroll() {
  if (spyTicking) return
  spyTicking = true
  requestAnimationFrame(() => {
    spyTicking = false
    updateActiveSection()
  })
}

function observeSections() {
  updateActiveSection()
}

onMounted(() => {
  window.addEventListener('scroll', onSpyScroll, { passive: true })
  // 初始 tab 先兜底高亮其首个 section，再按当前位置校正
  const first = firstSectionByTab[currentTopTab.value]
  if (first) activeSection.value = first
  updateActiveSection()
})

onBeforeUnmount(() => {
  window.removeEventListener('scroll', onSpyScroll)
})
</script>
